language: c
compiler:
  - gcc
  - clang
env:
  # Default build. Release.
  - BUILD_ARGS=""
  # Build using OpenSSL Libary for MD5/SHA1 hash functions
  - BUILD_ARGS="--with-openssl"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install automake1.9
script: 
  - autoreconf --install && ./configure $BUILD_ARGS && make && make check && ./ike-scan -v -v -v --vidpatterns=ike-vendor-ids --sport=1024 --dport=1024 127.0.0.1
